package com.entity;

import com.github.pagehelper.PageInfo;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;

public class SchJob{
    /**
     * 序列号
     *
     * Integet 类型是否改为Short
     *此处为ID生成器的ID
     */
    //@ApiModelProperty(value = "序列号",required = true);
    private Integer id;

    /**
     * 作业编号
     */
    @ApiModelProperty(value = "作业编号",required = true)
    private String jobId;

    /**
     * 作业名称
     */
    @ApiModelProperty(value = "作业名称",required = true)
    private String jobName;

    /**
     * 作业优先级
     */
    @ApiModelProperty(value = "作业优先级",required = true)
    private Byte jobLevel;

    /**
     * 作业执行服务名称
     */
    @ApiModelProperty(value = "作业执行服务名称",required = true)
    private String jobServerName;

    /**
     * 作业描述
     */
    @ApiModelProperty(value = "作业描述",required = true)
    private String jobDesc;

    /**
     * 是否有子作业
     */
    @ApiModelProperty(value = "是否有子作业",required = true)
    private Boolean isSubJob;

    /**
     * 是否等待
     */
    @ApiModelProperty(value = "是否等待",required = true)
    private Boolean isWait;

    /**
     * 是否删除
     */
    @ApiModelProperty(value = "是否删除",required = true)
    private Boolean isDeleted;

    /**
     * 创建时间
     */
    @ApiModelProperty(value = "创建时间",required = true)
    private Date createTime;

    /**
     * 更新时间
     */
    @ApiModelProperty(value = "更新时间",required = true)
    private Date updateTime;

    /**
     * 更新用户
     */
    @ApiModelProperty(value = "更新用户",required = true)
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sch_job
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sch_job.id
     *
     * @return the value of sch_job.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sch_job.id
     *
     * @param id the value for sch_job.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sch_job.job_id
     *
     * @return the value of sch_job.job_id
     *
     * @mbggenerated
     */
    public String getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sch_job.job_id
     *
     * @param jobId the value for sch_job.job_id
     *
     * @mbggenerated
     */
    public void setJobId(String jobId) {
        this.jobId = jobId == null ? null : jobId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sch_job.job_name
     *
     * @return the value of sch_job.job_name
     *
     * @mbggenerated
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sch_job.job_name
     *
     * @param jobName the value for sch_job.job_name
     *
     * @mbggenerated
     */
    public void setJobName(String jobName) {
        this.jobName = jobName == null ? null : jobName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sch_job.job_level
     *
     * @return the value of sch_job.job_level
     *
     * @mbggenerated
     */
    public Byte getJobLevel() {
        return jobLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sch_job.job_level
     *
     * @param jobLevel the value for sch_job.job_level
     *
     * @mbggenerated
     */
    public void setJobLevel(Byte jobLevel) {
        this.jobLevel = jobLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sch_job.job_server_name
     *
     * @return the value of sch_job.job_server_name
     *
     * @mbggenerated
     */
    public String getJobServerName() {
        return jobServerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sch_job.job_server_name
     *
     * @param jobServerName the value for sch_job.job_server_name
     *
     * @mbggenerated
     */
    public void setJobServerName(String jobServerName) {
        this.jobServerName = jobServerName == null ? null : jobServerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sch_job.job_desc
     *
     * @return the value of sch_job.job_desc
     *
     * @mbggenerated
     */
    public String getJobDesc() {
        return jobDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sch_job.job_desc
     *
     * @param jobDesc the value for sch_job.job_desc
     *
     * @mbggenerated
     */
    public void setJobDesc(String jobDesc) {
        this.jobDesc = jobDesc == null ? null : jobDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sch_job.is_sub_job
     *
     * @return the value of sch_job.is_sub_job
     *
     * @mbggenerated
     */
    public Boolean getIsSubJob() {
        return isSubJob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sch_job.is_sub_job
     *
     * @param isSubJob the value for sch_job.is_sub_job
     *
     * @mbggenerated
     */
    public void setIsSubJob(Boolean isSubJob) {
        this.isSubJob = isSubJob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sch_job.is_wait
     *
     * @return the value of sch_job.is_wait
     *
     * @mbggenerated
     */
    public Boolean getIsWait() {
        return isWait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sch_job.is_wait
     *
     * @param isWait the value for sch_job.is_wait
     *
     * @mbggenerated
     */
    public void setIsWait(Boolean isWait) {
        this.isWait = isWait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sch_job.is_deleted
     *
     * @return the value of sch_job.is_deleted
     *
     * @mbggenerated
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sch_job.is_deleted
     *
     * @param isDeleted the value for sch_job.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sch_job.create_time
     *
     * @return the value of sch_job.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sch_job.create_time
     *
     * @param createTime the value for sch_job.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sch_job.update_time
     *
     * @return the value of sch_job.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sch_job.update_time
     *
     * @param updateTime the value for sch_job.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sch_job.update_by
     *
     * @return the value of sch_job.update_by
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sch_job.update_by
     *
     * @param updateBy the value for sch_job.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }
}